version: "3.8"
services:
  db:
    build: ./dbFiles
    image: another_db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=Severly
    ports:
      - '5432:5432'
  api:
    build: ./express-api
    image: another_api
    depends_on:
      - db
    ports:
      - "4321:4321"
  web:
    build: ./react-client
    image: react_web
    depends_on:
      - api
    ports:
      - "3000:3000"
